import type { ExamConfig, ExamQuestion } from "@/components/ExamEngine";

export const CONFIG: ExamConfig = {
  moduleId: 1,
  gameId: 1,
  title: "Safe Driving Knowledge Exam",
  subtitle: "Module 1 . Game 1 of 4",
  icon: "Q",
  totalTimeSeconds: 25 * 60,
  pointsCorrect: 10,
  pointsWrong: -5,
  passPct: 70,
};

export const QUESTIONS: ExamQuestion[] = [
  {
    id: 1,
    question: "Among the following sets, which one correctly lists ALL SIX vehicle checks a driver is required to verify before any journey?",
    options: [
      { id:"a", text:"Brake condition, Lighting condition, Wipers, Horn, Side mirrors, Tyre condition", isCorrect:true },
      { id:"b", text:"Brake condition, Fuel level, Wipers, Horn, Air-conditioning, Tyre condition", isCorrect:false },
      { id:"c", text:"Lighting condition, Wipers, Horn, Side mirrors, Tyre condition, Seat position", isCorrect:false },
      { id:"d", text:"Brake condition, Lighting condition, Engine oil, Horn, Side mirrors, Radio", isCorrect:false },
      { id:"e", text:"Brake condition, Lighting condition, Wipers, GPS, Side mirrors, Tyre condition", isCorrect:false },
      { id:"f", text:"Fuel level, Lighting condition, Wipers, Horn, Side mirrors, Tyre condition", isCorrect:false },
    ],
  },
  {
    id: 2,
    question: "On a long-distance journey, what is the minimum rest requirement a driver must observe?",
    options: [
      { id:"a", text:"A 5-minute pause every hour", isCorrect:false },
      { id:"b", text:"A 15-minute break after every 2 hours of driving", isCorrect:true },
      { id:"c", text:"A 30-minute break after every 4 hours of driving", isCorrect:false },
      { id:"d", text:"No break needed if the driver feels alert", isCorrect:false },
      { id:"e", text:"A 10-minute break after every 3 hours", isCorrect:false },
      { id:"f", text:"A 1-hour break after every 5 hours", isCorrect:false },
    ],
  },
  {
    id: 3,
    question: "If drowsiness sets in while driving, which response is the recommended best practice (not merely a temporary fix)?",
    options: [
      { id:"a", text:"Increase the radio volume", isCorrect:false },
      { id:"b", text:"Open the window for fresh air", isCorrect:false },
      { id:"c", text:"Stop and rest immediately", isCorrect:true },
      { id:"d", text:"Continue driving at a slower speed", isCorrect:false },
      { id:"e", text:"Drink a caffeinated beverage and continue", isCorrect:false },
      { id:"f", text:"Turn the air-conditioning to maximum", isCorrect:false },
    ],
  },
  {
    id: 4,
    question: "Study the scene shown. What unsafe condition is being illustrated?",
    image: true,
    imageCaption: "Driver dozing off behind the wheel",
    options: [
      { id:"a", text:"Dozing off / driving while fatigued", isCorrect:true },
      { id:"b", text:"Tailgating the vehicle ahead", isCorrect:false },
      { id:"c", text:"Exceeding the speed limit", isCorrect:false },
      { id:"d", text:"Using a handphone while driving", isCorrect:false },
      { id:"e", text:"Driving without a seatbelt", isCorrect:false },
      { id:"f", text:"Failing to check a blind spot", isCorrect:false },
    ],
  },
  {
    id: 5,
    question: "What is the standard industry name given to the rule governing safe vehicle following distance?",
    options: [
      { id:"a", text:"The 2-Second Rule", isCorrect:false },
      { id:"b", text:"The 3-Second Rule", isCorrect:true },
      { id:"c", text:"The 5-Second Rule", isCorrect:false },
      { id:"d", text:"The Braking Distance Rule", isCorrect:false },
      { id:"e", text:"The Following Gap Law", isCorrect:false },
      { id:"f", text:"The Stopping Sight Rule", isCorrect:false },
    ],
  },
  {
    id: 6,
    question: "What is the minimum timing gap that must be maintained from the vehicle ahead under this rule?",
    options: [
      { id:"a", text:"1 second", isCorrect:false },
      { id:"b", text:"2 seconds", isCorrect:false },
      { id:"c", text:"3 seconds", isCorrect:true },
      { id:"d", text:"4 seconds", isCorrect:false },
      { id:"e", text:"5 seconds", isCorrect:false },
      { id:"f", text:"6 seconds", isCorrect:false },
    ],
  },
  {
    id: 7,
    question: "What unsafe behaviour is illustrated in this scene?",
    image: true,
    imageCaption: "Driver not wearing a seatbelt",
    options: [
      { id:"a", text:"Not wearing a seatbelt", isCorrect:true },
      { id:"b", text:"Exceeding the speed limit", isCorrect:false },
      { id:"c", text:"Using a handphone while driving", isCorrect:false },
      { id:"d", text:"Failing to signal before turning", isCorrect:false },
      { id:"e", text:"Driving while fatigued", isCorrect:false },
      { id:"f", text:"Tailgating the vehicle ahead", isCorrect:false },
    ],
  },
  {
    id: 8,
    question: "Beyond the safety risk itself, what financial consequence can result from failing to wear a seatbelt in Malaysia?",
    options: [
      { id:"a", text:"A RM100 fine", isCorrect:false },
      { id:"b", text:"A RM300 fine", isCorrect:true },
      { id:"c", text:"A RM500 fine", isCorrect:false },
      { id:"d", text:"No financial penalty, warning only", isCorrect:false },
      { id:"e", text:"A RM1000 fine", isCorrect:false },
      { id:"f", text:"Immediate licence suspension", isCorrect:false },
    ],
  },
  {
    id: 9,
    question: "What unsafe behaviour is illustrated in this scene?",
    image: true,
    imageCaption: "Driver looking at a handphone",
    options: [
      { id:"a", text:"Reckless overtaking", isCorrect:false },
      { id:"b", text:"Distracted driving / using a handphone", isCorrect:true },
      { id:"c", text:"Not wearing a seatbelt", isCorrect:false },
      { id:"d", text:"Tailgating the vehicle ahead", isCorrect:false },
      { id:"e", text:"Ignoring road signage", isCorrect:false },
      { id:"f", text:"Driving without headlights", isCorrect:false },
    ],
  },
  {
    id: 10,
    question: "What is the most effective correction for the behaviour shown in the previous scene?",
    options: [
      { id:"a", text:"Keep the phone on speaker mode instead", isCorrect:false },
      { id:"b", text:"Use a hands-free device only", isCorrect:false },
      { id:"c", text:"Avoid using the handphone entirely and stay focused on the road", isCorrect:true },
      { id:"d", text:"Lower the notification volume", isCorrect:false },
      { id:"e", text:"Glance at the phone only at red lights", isCorrect:false },
      { id:"f", text:"Place the phone on the dashboard within reach", isCorrect:false },
    ],
  },
  {
    id: 11,
    question: "What unsafe driving behaviour does this scene depict?",
    image: true,
    imageCaption: "Vehicle rushing through traffic recklessly",
    options: [
      { id:"a", text:"Rushing and reckless / dangerous driving", isCorrect:true },
      { id:"b", text:"Poor use of vehicle lighting", isCorrect:false },
      { id:"c", text:"Improper side mirror use", isCorrect:false },
      { id:"d", text:"Ignoring signs of fatigue", isCorrect:false },
      { id:"e", text:"Incorrect tyre pressure", isCorrect:false },
      { id:"f", text:"Failure to give a turn signal", isCorrect:false },
    ],
  },
  {
    id: 12,
    question: "Which of these is NOT a documented consequence of rushing or driving recklessly?",
    options: [
      { id:"a", text:"Decreased reaction time", isCorrect:false },
      { id:"b", text:"Impaired vehicle control", isCorrect:false },
      { id:"c", text:"Greater impact force in a collision", isCorrect:false },
      { id:"d", text:"Improved fuel efficiency", isCorrect:true },
      { id:"e", text:"Elevated risk of secondary accidents", isCorrect:false },
      { id:"f", text:"Increased danger to other road users", isCorrect:false },
    ],
  },
  {
    id: 13,
    question: "What hazardous behaviour is illustrated in this scene?",
    image: true,
    imageCaption: "Driver changing lanes without checking mirrors",
    options: [
      { id:"a", text:"Not checking side mirrors / blind spot, no signal given", isCorrect:true },
      { id:"b", text:"Speeding through a school zone", isCorrect:false },
      { id:"c", text:"Driving on worn tyres", isCorrect:false },
      { id:"d", text:"Ignoring poor weather conditions", isCorrect:false },
      { id:"e", text:"Overloading the vehicle", isCorrect:false },
      { id:"f", text:"Driving without headlights at night", isCorrect:false },
    ],
  },
  {
    id: 14,
    question: "Before changing lanes, overtaking, or turning at a junction, how many seconds of signal must be given according to the official briefing?",
    options: [
      { id:"a", text:"2 seconds", isCorrect:false },
      { id:"b", text:"3 seconds", isCorrect:false },
      { id:"c", text:"4 seconds", isCorrect:false },
      { id:"d", text:"5 seconds", isCorrect:false },
      { id:"e", text:"6 seconds", isCorrect:true },
      { id:"f", text:"8 seconds", isCorrect:false },
    ],
  },
  {
    id: 15,
    question: "The 3-second following distance breaks down into three phases. Which sequence correctly matches each second to its purpose?",
    options: [
      { id:"a", text:"1st: recognise the danger, 2nd: react and apply brakes, 3rd: tyres grip and vehicle stops", isCorrect:true },
      { id:"b", text:"1st: apply brakes, 2nd: recognise the danger, 3rd: vehicle stops", isCorrect:false },
      { id:"c", text:"1st: vehicle stops, 2nd: react, 3rd: recognise the danger", isCorrect:false },
      { id:"d", text:"1st: react and brake, 2nd: tyres grip and stop, 3rd: recognise the danger", isCorrect:false },
      { id:"e", text:"1st: tyres grip, 2nd: recognise the danger, 3rd: react and brake", isCorrect:false },
      { id:"f", text:"1st: recognise the danger, 2nd: vehicle stops, 3rd: react and brake", isCorrect:false },
    ],
  },
];
